//@Library(['drp-jenkins-lib@main', 'jenkins-global-lib@main']) _
//CommonLibPipeline

import groovy.transform.Field

@Field String TOPIC = PipelineVariables.techOpsKafkaTopic

def pipelineParams = [:]

pipeline {
    agent {
        kubernetes {
            yaml libraryResource('containerBuildPod.yaml')
            showRawYaml(false)
            defaultContainer 'python'
        }
    }

    environment {
        PYPIRC_FILE = "./ci/stg-pypirc"
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '10'))
        timestamps()
        timeout(activity: true, time: 60, unit: 'MINUTES')
    }

    stages {
        stage('Configure Build Containers') {
            when { expression { currentBuild.currentResult == 'SUCCESS' } }
            steps {
		sh """
		    source activate
		    python -m build
		"""
            }
        }

        stage('Push Package') {
            when {
                allOf {
                    expression { currentBuild.currentResult == 'SUCCESS' }
                    anyOf {
                        branch 'main'
                    }
                }
            }
            steps {
              withCredentials([usernamePassword(credentialsId: '1a69cdbb-be20-4bde-b30a-87ef9b2db969', passwordVariable: 'TWINE_PASSWORD', usernameVariable: 'TWINE_USERNAME')]) {
		sh """
		    source activate
	            python -m twine upload --verbose --disable-progress-bar --non-interactive  --repository devpi ./dist/* --config-file $PYPIRC_FILE
	        """
              }
            }
        }
    }

    post {
        always {
            kafkaBuildReporter()
        }
        cleanup {
            deleteDir()
        }
    }
}
